let g:lsp_fold_enabled = 1
let g:lsp_diagnostics_enabled = 1
let g:lsp_signs_enabled = 1
let g:lsp_diagnostics_echo_cursor = 1
let g:lsp_signs_error = {'text': '🚫'}
let g:lsp_signs_warning = {'text': '⚠️'} " icons require GUI
let g:lsp_signs_hint = {'text': '🔍'} " icons require GUI
let g:lsp_highlights_enabled = 1
let g:lsp_textprop_enabled = 1
let g:lsp_highlight_references_enabled = 1
